coder/coder-desktop-macos

- Coder Desktop/.swiftlint.yml
- Coder Desktop/Coder Desktop.xcodeproj/project.pbxproj
- Coder Desktop/Coder Desktop.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Coder Desktop/Coder Desktop.xcodeproj/xcshareddata/xcschemes/Coder Desktop.xcscheme
- Coder Desktop/Coder Desktop.xctestplan
- Coder Desktop/Coder Desktop/About.swift
- Coder Desktop/Coder Desktop/Coder_DesktopApp.swift
- Coder Desktop/Coder Desktop/Preview Content/PreviewClient.swift
- Coder Desktop/Coder Desktop/Preview Content/PreviewSession.swift
- Coder Desktop/Coder Desktop/Preview Content/PreviewVPN.swift
- Coder Desktop/Coder Desktop/SDK/Client.swift
- Coder Desktop/Coder Desktop/SDK/Date.swift
- Coder Desktop/Coder Desktop/SDK/User.swift
- Coder Desktop/Coder Desktop/Session.swift
- Coder Desktop/Coder Desktop/Theme.swift
- Coder Desktop/Coder Desktop/VPNService.swift
- Coder Desktop/Coder Desktop/Views/Agents.swift
- Coder Desktop/Coder Desktop/Views/AuthButton.swift
- Coder Desktop/Coder Desktop/Views/LoginForm.swift
- Coder Desktop/Coder Desktop/Views/Util.swift
- Coder Desktop/Coder Desktop/Views/VPNMenu.swift
- Coder Desktop/Coder Desktop/Views/VPNState.swift
- Coder Desktop/Coder Desktop/Windows.swift
- Coder Desktop/Coder DesktopTests/AgentsTests.swift
- Coder Desktop/Coder DesktopTests/LoginFormTests.swift
- Coder Desktop/Coder DesktopTests/Util.swift
- Coder Desktop/Coder DesktopTests/VPNMenuTests.swift
- Coder Desktop/Coder DesktopTests/VPNStateTests.swift
- Coder Desktop/Coder DesktopUITests/Coder_DesktopUITests.swift
- Coder Desktop/Coder DesktopUITests/Coder_DesktopUITestsLaunchTests.swift
Closes #3.
Relates to #4.
- Adds a stock `About` popup.
- Adds a `SecureSession` that writes the session token to the keychain, and the server URL to `UserDefaults`.
- Adds an initial `Client` for the Swift `coderd` SDK. Currently only supports the `users` endpoint for validating a session token.
https://github.com/user-attachments/assets/9224702e-73db-4b67-85b7-d285003cb315
The 'generate a token' hyperlink takes the user to `/cli-auth`.
> feat: add login flow & session management

- Coder Desktop/Coder Desktop.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Coder Desktop/Coder Desktop/Preview Content/PreviewClient.swift
- Coder Desktop/Coder Desktop/SDK/Client.swift
- Coder Desktop/Coder Desktop/SDK/User.swift
- Coder Desktop/Coder Desktop/Views/LoginForm.swift
- Coder Desktop/Coder DesktopTests/AgentsTests.swift
- Coder Desktop/Coder DesktopTests/LoginFormTests.swift
- Coder Desktop/Coder DesktopTests/Util.swift
- Coder Desktop/Coder DesktopTests/VPNMenuTests.swift
- Coder Desktop/Coder DesktopTests/VPNStateTests.swift
Cleanup PR to:
- Handle error responses from SDK, improve the error handling
- Replace the login flow errors with a popup, so we can actually display the full error
- Update ViewInspector and fix a deprecation warning in the tests
> chore: add API errors to SDK

- Coder Desktop/Coder Desktop.xcodeproj/project.pbxproj
- Coder Desktop/Coder Desktop.xcodeproj/xcshareddata/xcschemes/ProtoTests.xcscheme
- Coder Desktop/Proto/Receiver.swift
- Coder Desktop/Proto/Speaker.swift
- Coder Desktop/ProtoTests/SpeakerTests.swift
Upgrades Proto to Swift 6, mostly by telling the compiler explicitly that things are sendable, but in some cases by scoping down our closures so they only capture sendable objects.
> chore: upgrade Proto code to Swift 6

- Coder Desktop/Proto/Receiver.swift
- Coder Desktop/Proto/Speaker.swift
- Coder Desktop/ProtoTests/SpeakerTests.swift
Instead of relying on class inheritance, the new Speaker can composed into whatever would like to speak the CoderVPN protocol, and messages can be handled by iterating over the speaker itself e.g:
```swift
enum IncomingMessage {
case message(RecvMsg)
case RPC(RPCRequest<SendMsg, RecvMsg>)
}
```
```swift
for try await msg in speaker {
switch msg {
case let .message(msg):
// Handle message that doesn't require a response
case let .RPC(req):
// Handle incoming RPC
}
}
```
> chore: refactor speaker & handshaker into actors

- Coder Desktop/Coder Desktop.xcodeproj/project.pbxproj
- Coder Desktop/Coder Desktop/Coder_Desktop.entitlements
- Coder Desktop/Coder Desktop/Coder_DesktopApp.swift
- Coder Desktop/Coder Desktop/NetworkExtension.swift
- Coder Desktop/Coder Desktop/Preview Content/PreviewSession.swift
- Coder Desktop/Coder Desktop/Preview Content/PreviewVPN.swift
- Coder Desktop/Coder Desktop/Session.swift
- Coder Desktop/Coder Desktop/SystemExtension.swift
- Coder Desktop/Coder Desktop/VPNService.swift
- Coder Desktop/Coder DesktopTests/VPNMenuTests.swift
- Coder Desktop/Coder DesktopTests/VPNStateTests.swift
- Coder Desktop/VPN/Info.plist
- Coder Desktop/VPN/PacketTunnelProvider.swift
- Coder Desktop/VPN/VPN.entitlements
With apologies, I'm sort of punting on this one for the time being.
The code works to install and allow activation of the Network Extension, but for some reason the delegate I've created to get updates about the System Extension installation is not getting called back.
I've posted on the Apple Developer Forums about it: https://forums.developer.apple.com/forums/thread/772236
In the meantime, I'm hoping to get some feedback about the code and overall design. I'll leave it in draft for now.
> feat: install and activate the tunnel provider as network extension

- Coder Desktop/Coder DesktopTests/Util.swift
- Makefile
Tests that didn't compile got merged to main because `pipefail` wasn't set when piping the output of `xcodebuild` into `xcpretty`.
> fix: set pipefail during make test

- Coder Desktop/Coder Desktop/SystemExtension.swift
- Coder Desktop/Coder Desktop/VPNService.swift
The problem we were having before was being caused by the system extension delegate being deallocated before the request responses came back.
I didn't initially realize this, but the [OSSystemRequest.delegate](https://developer.apple.com/documentation/systemextensions/ossystemextensionrequest/delegate) is a weak reference (you have to click down to the individual field view in the docs to learn this).
So, we keep a strong reference from the VPNService around while we are waiting for the extension to install.
> fix: hold delegate reference to keep it from being deallocated

- Coder Desktop/Coder Desktop/Coder_DesktopApp.swift
- Coder Desktop/Coder Desktop/Preview Content/PreviewVPN.swift
- Coder Desktop/Coder Desktop/VPNService.swift
- Coder Desktop/Coder Desktop/Views/VPNMenu.swift
When the app is quit (terminated), in any way, an active VPN connection should first be shutdown by sending the stop response over the tunnel. Previously we were only catching when the app was closed via the quit button we supply, but we can actually catch any non-force-quit terminations using the `AppDelegate`.
Additionally:
- Quitting the app while the VPN is stopping should wait for the existing stop operation to finish
- Quitting the app while the VPN is starting should wait for the start operation to finish, and then start and wait for a stop operation.
> chore: gracefully shutdown app

- Coder Desktop/Coder Desktop/Coder_DesktopApp.swift
- Coder Desktop/Coder Desktop/Views/LoginForm.swift
Definitely not a super crucial change, but this brings the login form styling in-line with the settings menu that I'm currently working on (for literal HTTP headers). 
https://github.com/user-attachments/assets/bab5c35f-6da7-45a7-acae-59ca90aefaf7
Also binds `esc` via `.cancelAction` to both the `Cancel` and `Back` buttons.
> chore: improve login form styling

- Coder Desktop/Coder Desktop.xcodeproj/project.pbxproj
- Coder Desktop/Coder Desktop.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Coder Desktop/Coder Desktop/About.swift
- Coder Desktop/Coder Desktop/Coder_DesktopApp.swift
- Coder Desktop/Coder Desktop/State.swift
- Coder Desktop/Coder Desktop/Views/LoginForm.swift
- Coder Desktop/Coder Desktop/Views/Settings/GeneralTab.swift
- Coder Desktop/Coder Desktop/Views/Settings/LiteralHeaderModal.swift
- Coder Desktop/Coder Desktop/Views/Settings/LiteralHeadersSection.swift
- Coder Desktop/Coder Desktop/Views/Settings/NetworkTab.swift
- Coder Desktop/Coder Desktop/Views/Settings/Settings.swift
- Coder Desktop/Coder Desktop/Views/Util.swift
- Coder Desktop/Coder Desktop/Views/VPNMenu.swift
- Coder Desktop/Coder Desktop/Windows.swift
- Coder Desktop/Coder DesktopTests/LiteralHeadersSettingTests.swift
- Coder Desktop/Coder DesktopTests/LoginFormTests.swift
- Makefile
First step for #17.
This PR adds a settings menu to the app, and a network tab with a form for specifying hard-coded HTTP headers to be added on all outgoing requests. The settings cannot be modified while Coder VPN is on, as they can't be applied to the DERP headers without restarting the tailnet connection.
https://github.com/user-attachments/assets/167ad1de-ca8a-4c88-829f-219d50fd1d00
Future work includes:
- Sending these headers to the Network Extension whenever they change, via XPC.
- Adding support for dynamic, shell command-based headers, as also supported by the CLI.
> feat: support user-supplied literal headers

- Coder Desktop/Coder Desktop.xcodeproj/project.pbxproj
- Coder Desktop/Coder Desktop/Coder_DesktopApp.swift
- Coder Desktop/Coder Desktop/NetworkExtension.swift
- Coder Desktop/Coder Desktop/VPNService.swift
- Coder Desktop/VPN/Manager.swift
- Coder Desktop/VPN/PacketTunnelProvider.swift
- Coder Desktop/VPN/TunnelHandle.swift
- Coder Desktop/VPN/VPN.entitlements
- Coder Desktop/VPNLib/Util.swift
The Go dylib `OpenTunnel` function blocks until the handshake is performed over the file descriptors, so we'll run that function on a different thread, and then await that it returns.
A few other cleanups throughout to get Manager's `init` to run to completion: downloading and validating the dylib and starting the tunnel.
> fix: concurrently open tunnel & handshake

- .gitignore
- Coder Desktop/.swiftformat
- Coder Desktop/Coder Desktop/Coder_DesktopApp.swift
- Coder Desktop/Coder Desktop/State.swift
- Coder Desktop/VPN/Manager.swift
- Coder Desktop/VPN/PacketTunnelProvider.swift
- Coder Desktop/VPNLib/Convert.swift
- Coder Desktop/VPNLib/Receiver.swift
- Coder Desktop/VPNLib/Speaker.swift
- Coder Desktop/VPNLib/Util.swift
- Coder Desktop/VPNLibTests/ConvertTests.swift
- Makefile
This PR:
- Passes the session token to the network extension via the VPN configuration (see #33)
- Properly applies tunnel settings by layering multiple requests from the dylib (as DNS settings are sent seperately from IP addresses and routes)
With this, the VPN functionality works end-to-end! Once the system extension is enabled, and the app has been logged in, starting the VPN will make the user's workspaces available on `<wsname>.coder`
> chore: pass session token to network extension

- Coder Desktop/Coder Desktop/Coder_DesktopApp.swift
- Coder Desktop/Coder Desktop/NetworkExtension.swift
- Coder Desktop/Coder Desktop/State.swift
- Coder Desktop/Coder Desktop/SystemExtension.swift
- Coder Desktop/Coder Desktop/VPNService.swift
- Coder Desktop/Coder Desktop/Views/Settings/GeneralTab.swift
- Coder Desktop/Coder Desktop/XPCInterface.swift
- Coder Desktop/VPN/Manager.swift
- Coder Desktop/VPN/XPCInterface.swift
- Coder Desktop/VPNLib/XPC.swift
Currently, CoderVPN disables it's system-level configuration when it's turned off. This means it can't be started and stopped from System Preferences. Since the network extension works fine without the app, we can remove this restriction.
However, it then becomes necessary to retrieve the state of the peers (agents) when starting the app whilst the VPN is running. We already have support for this on the dylib side, so this PR wires that functionality up over XPC.
Demo (I launch the app once the VPN reports itself as connected):
https://github.com/user-attachments/assets/53798b63-8b4e-4870-be99-ebafda173bca
This behaviour is only present in a Release build of the app. In a Debug build, launching the app will trigger a replacement of the network extension installed on the system, but not …
> chore: support operating the VPN without the app

- .github/workflows/release.yml
- Makefile
Fixed release asset upload and version parsing
Using a glob pattern, the release workflow now correctly uploads all assets from the output directory. Version parsing in the Makefile has been updated to handle pre-release tags by removing trailing pre-release identifiers.
Change-Id: I15b816393880406c9ac6a7cbbd2b3344c338894c
> fix(Makefile): remove suffix after patch number

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Makefile
Adds validation for version variables in Makefile
Ensures CURRENT_PROJECT_VERSION and MARKETING_VERSION are not empty when building the project, failing the build process with an error message if either variable cannot be determined from git tags.
Change-Id: I83265a11182df6d28f2ef3a5f5454adba27c95ea
> fix(Makefile): add version validation checks

- Coder Desktop/Coder Desktop/Views/LoginForm.swift
Closes #53.
The linked issue was caused by a subtle difference in how we add paths to the server URLs in Go and Swift
In both languages, the (erroneous) url `https:/dev.coder.com` is parsed the same:
- Scheme: `https`
- Host: "" / `nil`
- Relative Path: `/dev.coder.com`
However, in Swift, when we transform a server URL into a specific route on that server, such as `/api/v2/users/me`, we don't replace any existing part of the relative path, we just append to it, producing `http:/dev.coder.com/api/v2/users/me`, which gets sent, and the server responds to, just fine.
In Go, when we do the same transformation, we call `svrURL.Parse("/api/v2/users/me")`, which replaces the existing relative path, `/dev.coder.com`, leading to the error in the linked issue, which has no `dev.coder.com` portion …
> fix: validate server URL has a host

- Coder Desktop/Coder Desktop/Views/LoginForm.swift
- Coder Desktop/Coder Desktop/Views/ResponsiveLink.swift
Closes #55.
https://github.com/user-attachments/assets/baf53b88-1471-4057-835f-eaddbd583d75
> chore: make cli-auth link visually responsive

- scripts/update-cask.sh
Reorder cask conflicts and add SHA256 no_check for preview builds
Change-Id: I7ff8b3d09fb2ac95c66ee67930a00a4e0f6aab6b
> ci: fix brew cask formatting

- Coder Desktop/Coder Desktop/State.swift
- Coder Desktop/Coder Desktop/Views/Settings/LiteralHeaderModal.swift
- Coder Desktop/Coder Desktop/Views/Settings/LiteralHeadersSection.swift
- Coder Desktop/CoderSDK/Client.swift
- Coder Desktop/CoderSDK/HTTP.swift
- Coder Desktop/CoderSDKTests/CoderSDKTests.swift
- Coder Desktop/VPN/Manager.swift
- Coder Desktop/VPN/PacketTunnelProvider.swift
> fix: pass configured http headers to network extension

- .github/workflows/ci.yml
- .github/workflows/release.yml
Add concurrency groups to GitHub Actions workflows
Adds concurrency groups to CI and release workflows to automatically cancel
in-progress runs when new changes are pushed. This prevents unnecessary
resource usage and speeds up feedback loops for developers.
Change-Id: I781ce2750eb30729e84430ee2e3855f3259d2eb9
> ci: add concurrency groups to release pipeline

- Coder Desktop/Coder Desktop/VPNMenuState.swift
- Coder Desktop/Coder Desktop/VPNService.swift
- Coder Desktop/Coder Desktop/Views/VPNMenu.swift
- Coder Desktop/VPN/Manager.swift
- Coder Desktop/VPN/PacketTunnelProvider.swift
- Coder Desktop/VPNLib/Download.swift
- Coder Desktop/VPNLibTests/DownloadTests.swift
Depends on https://github.com/coder/coder/pull/16598.
Reverts #43.
Whilst everything seems to recover okay tailnet wise when waking from sleep currently, the tunnel will still miss workspace/peer updates during the sleep, causing the workspace state in the UI to be out of sync with reality. 
To handle this, we'll teardown the tunnel on sleep, and bring it back up on wake.
Fixing the issue in `coder/coder` also revealed that the error encountered when toggling the VPN on and off quickly was another symptom, and so this change reverts the code that prevents toggling the VPN on and off quickly, as it now works flawlessly.
> chore: handle waking from device sleep

- Coder Desktop/Coder Desktop/Coder_DesktopApp.swift
- Coder Desktop/Coder Desktop/NetworkExtension.swift
- Coder Desktop/Coder Desktop/VPNService.swift
- Coder Desktop/Coder Desktop/Views/LoginForm.swift
- Coder Desktop/Coder Desktop/Views/VPNMenu.swift
- Coder Desktop/CoderSDK/Client.swift
- Coder Desktop/VPN/Manager.swift
- Coder Desktop/VPN/TunnelHandle.swift
- Coder Desktop/VPNLib/Download.swift
- Coder Desktop/VPNLib/Receiver.swift
- Coder Desktop/VPNLib/Speaker.swift
Logging into Coder Desktop configures the system VPN with the session token & server URL.
However, uninstalling the app does not remove clear the `UserDefault` settings (namely `hasSession`), nor does it clear the keychain item (containing the session token). This means a fresh install of the app (that involves deleting the network extension from settings) starts in a broken state: 
The VPN looks like it can be used, as typically the NE is configured once logged in, but the deleting of the network extension cleared the configuration. Right now we show an error that suggests logging out and back in.
This PR makes it not possible to enter this broken state. If a NE configuration cannot be loaded on start up of the app, the session is cleared, and the user will see they need to log in again. …
> chore: clear session on launch if vpn unconfigured

- scripts/update-cask.sh
Fix homebrew cask styling, as it complained about incorrectly ordered keys and spacing.
Change-Id: I02234e007ce2f37074779211ab6c102cb4213122
> ci: Fix homebrew cask styling

- Coder Desktop/Coder Desktop/Views/LoginForm.swift
- Coder Desktop/CoderSDK/Client.swift
- Coder Desktop/VPN/Manager.swift
- Coder Desktop/VPN/TunnelHandle.swift
- Coder Desktop/VPNLib/Download.swift
Before & After:
We always want to show the `localizedDescription`, and rarely anything else. These long errors make for a pretty poor UX. Logs are unchanged.
> chore: reduce error verbosity

- Coder Desktop/Coder Desktop/VPNMenuState.swift
- Coder Desktop/Coder Desktop/Views/Agents.swift
- Coder Desktop/Coder Desktop/Views/VPNMenu.swift
- Coder Desktop/Coder Desktop/Views/VPNMenuItem.swift
- Coder Desktop/Coder Desktop/Views/VPNState.swift
I discovered you pretty much never want to use `gray` as a text colour. `secondary` is only gray where appropriate.
The menu bar tray is slightly transparent, and `.secondary` and `.primary` text colours account for that.
As seen below, dark mode is almost unchanged.
Note: Apple's decided to make `secondary` darker than `primary` in this case.
> chore: improve text contrast on light mode

- Coder Desktop/Coder Desktop/State.swift
- Coder Desktop/Coder Desktop/Views/LoginForm.swift
- Coder Desktop/Coder Desktop/Views/VPNMenu.swift
The preview was panicking because the app state had an optional base URL, which is getting unwrapped elsewhere. This creates an app state and then 'logs in' to set the base URL, reenabling the preview.
Change-Id: I8d6a19063a13f772dc409bc5e523e1af9c109bee
> fix: canvas preview panic in Xcode resolved

- Coder Desktop/Coder Desktop/Coder_DesktopApp.swift
- Coder Desktop/Coder Desktop/MenuBarIconController.swift
- Coder Desktop/Coder Desktop/State.swift
- Coder Desktop/Coder Desktop/Views/LoginForm.swift
- Coder Desktop/VPN/Manager.swift
Improvement over the change in #76 - reconfigures on launch if the VPN is unconfigured, but an existing session is present in `UserDefaults` & Keychain.
Additionally:
- Changes the waiting for connectivity timeout on the dylib download from 7 days to 15 seconds.
- Sets the icon to the 'off' opacity on startup. Previously it was only set to 'off' on startup if the VPN was configured. If the VPN is connected on startup, it'll immediately go back to the 'on' opacity.
> chore: reconfigure VPN on reinstall

- Coder Desktop/Coder Desktop/Views/VPNMenuItem.swift
Previously, if you clicked on the highlighted padding of the copy icon, the button wouldn't get pressed - this was really bothering me.
[Relevant.](https://www.hackingwithswift.com/quick-start/swiftui/how-to-control-the-tappable-area-of-a-view-using-contentshape)
> fix: make copy button padding clickable

- Coder Desktop/Coder DesktopTests/LoginFormTests.swift
- Coder Desktop/CoderSDK/Client.swift
- Coder Desktop/CoderSDK/Deployment.swift
- Coder Desktop/CoderSDK/User.swift
- Coder Desktop/CoderSDKTests/CoderSDKTests.swift
https://github.com/coder/coder/pull/16564 has the Coder server no longer send the `theme_preference` field  in a `/api/v2/user` response. 
The Swift `JSONDecoder` requires that a missing field be explicitly marked as optional, else the deserialization fails. To make it less likely this happens again, we'll only require `id` and `username` be present.
We'll do the same for the other SDK types and only require the minimum fields the app needs be present.
This PR also improves the error message on any decoding error:
> fix: handle missing user `theme_preference` on sign in

- scripts/update-cask.sh
Update cask script to use pkg instead of dmg
Updates the update-cask script to download and verify the CoderDesktop.pkg file instead of the previously used Coder.Desktop.dmg file.
Change-Id: I79e601684c94374f62f505e6bdf86c51f7a42d7e
> ci: fix cask update

- Coder Desktop/Coder Desktop/Views/LoginForm.swift
- Coder Desktop/Coder DesktopTests/LoginFormTests.swift
- Coder Desktop/VPN/Manager.swift
- Coder Desktop/VPNLib/Download.swift
This will cause Coder Desktop networking to fail to start unless the validated dylib is version `v2.20.0` or later. Obviously, using this build early would mean Coder Desktop would not work against our dogfood deployment.
> chore: enforce minimum coder server version of v2.20.0

- Coder Desktop/Coder Desktop/NetworkExtension.swift
- Coder Desktop/Coder Desktop/SystemExtension.swift
- Coder Desktop/Coder Desktop/Views/Settings/GeneralTab.swift
- Coder Desktop/Coder Desktop/Views/Settings/LiteralHeadersSection.swift
- Coder Desktop/Coder Desktop/Views/VPNMenu.swift
- Coder Desktop/Coder Desktop/Views/VPNState.swift
- Coder Desktop/Coder DesktopTests/VPNMenuTests.swift
- Coder Desktop/Coder DesktopTests/VPNStateTests.swift
- pkgbuild/scripts/postinstall
- pkgbuild/scripts/preinstall
Rename "CoderVPN" to "Coder Connect" in UI and system components
- Updates VPN-related text from "CoderVPN" to "Coder Connect" in UI components
- Changes network extension references from "VPN" to "NE" in system messages
- Updates VPN tunnel name from "CoderVPN" to "Coder" in network configuration
- Modifies installation scripts to use "Coder" as the VPN service name
> chore: remove "VPN" from setting description

- pkgbuild/scripts/postinstall
- pkgbuild/scripts/preinstall
Relates to #83.
It looks like deleting the app does indeed kill the NE process, so we should do that during `preinstall`.
In case the XPC issue we've been seeing is due to a race between the app being opened, and Gatekeeper ingesting the notarization ticket, we'll also force Gatekeeper to read the ticket by running `spctl -a` on the app bundle, and the extension bundle. The latter always fails, but an attempt to read it can't hurt.
> chore(pkgbuild): delete existing app during preinstall, `spctl --assess` during postinstall

- Coder-Desktop/Coder-Desktop/Coder_DesktopApp.swift
- Coder-Desktop/Coder-Desktop/State.swift
- Coder-Desktop/Coder-Desktop/Views/Settings/GeneralTab.swift
Relates to #104.
On-demand is a pretty big lift - in the meantime we'll add a 'start VPN on launch' config setting.
> feat: add start vpn on launch setting

- Coder-Desktop/Coder-Desktop/Coder_DesktopApp.swift
- Coder-Desktop/Coder-Desktop/State.swift
- Coder-Desktop/CoderSDK/Client.swift
- Coder-Desktop/project.yml
Closes #107.
When the menu bar icon is clicked, and the user is signed in, and the VPN is disabled, the app will check if the token is expired. If it is, the user will be signed out.
We could have checked this when the VPN is enabled, but the UX seemed worse, and the implementation would have been messy. We would have needed to sign the user out and show an error. Instead, we'll check for expiry in a scenario where the next user step would likely be an interaction that requires a session. 
This approach also future-proofs for when functionality becomes usable without the VPN.
> chore: sign user out if token is expired

- Coder-Desktop/Coder-Desktop/Coder_DesktopApp.swift
- Coder-Desktop/Coder-Desktop/VPN/VPNService.swift
- Coder-Desktop/Coder-DesktopTests/LoginFormTests.swift
This is a fix for #108. Previously we would start the VPN immediately on launch if the config option was true. This starting of the VPN raced with any concurrent upgrades of the network extension, causing the VPN to be started with a VPN config belonging to the older network extension, and producing a consistent error message: 
Instead, we should only start the VPN once we know that the system extension and VPN configuration are installed.
> fix: start coder connect on launch after SE is installed

- Coder-Desktop/Coder-Desktop/Preview Content/PreviewVPN.swift
- Coder-Desktop/Coder-Desktop/VPN/VPNService.swift
- Coder-Desktop/Coder-Desktop/Views/VPNMenu.swift
- Coder-Desktop/Coder-DesktopTests/Util.swift
- Coder-Desktop/Coder-DesktopTests/VPNMenuTests.swift
> chore: prompt for sign in when turning VPN on if signed out

- Coder-Desktop/Coder-Desktop/Coder_DesktopApp.swift
- Coder-Desktop/VPNLib/FileSync/FileSyncDaemon.swift
- Coder-Desktop/project.yml
This makes a few improvements to #98:
- The mutagen path & data directory can be now be configured on the MutagenDaemon, to support overriding it in tests (coming soon).
- A mutagen daemon failure now kills the process, such that can it be restarted (TBC).
- Makes start & stop transitions mutually exclusive via a semaphore, to account for actor re-entrancy.
- The start operation now waits for the daemon to respond to a version request before completing.
- The daemon is always started on launch, but then immediately stopped if it doesn't manage any file sync sessions, as to not run in the background unncessarily.
> chore: conditionally start file sync daemon

- flake.lock
Now we'll have `make test` output..
I went to go update the pkg on `nixpkgs` myself, but someone else got it to it two weeks ago!
> chore: update nix flake to include xcbeautify 2.27.0

- Coder-Desktop/Coder-Desktop/Preview Content/PreviewFileSync.swift
- Coder-Desktop/Coder-Desktop/Views/FileSync/FileSyncConfig.swift
- Coder-Desktop/Coder-Desktop/Views/FileSync/FileSyncSessionModal.swift
- Coder-Desktop/Coder-DesktopTests/Util.swift
- Coder-Desktop/VPNLib/FileSync/FileSyncDaemon.swift
- Coder-Desktop/VPNLib/FileSync/FileSyncManagement.swift
> chore: create & delete sync sessions over gRPC

- Coder-Desktop/Coder-Desktop/Preview Content/PreviewFileSync.swift
- Coder-Desktop/Coder-Desktop/Views/FileSync/FileSyncConfig.swift
- Coder-Desktop/Coder-DesktopTests/Util.swift
- Coder-Desktop/VPNLib/FileSync/FileSyncDaemon.swift
- Coder-Desktop/VPNLib/FileSync/FileSyncManagement.swift
Equivalent to `mutagen sync restart`, such as for resolving safety checks: https://mutagen.io/documentation/introduction/getting-started/#resetting-sessions
Also adds an error alert for all fallible operations on the config window.
> feat: support restarting file sync sessions

- Coder-Desktop/Coder-Desktop/Views/FileSync/FileSyncConfig.swift
- Coder-Desktop/VPNLib/FileSync/FileSyncSession.swift
- Coder-Desktop/VPNLib/FileSync/MutagenConvert.swift
Last QoL PR for now..
This adds buttons to the alt click context menu:
And it adds a brief description of each conflict to the status tooltip:
There's three cases for now. The first is just a basic file conflict, the second is if there's a type conflict (file, directory, symlink, etc), and the third is self-explanatory.
We'll need to come up with a proper design for how we show conflicts, so this implementation is just to not leave users in the dark if they run into any.
> feat: add conflict descriptions and file sync context menu

- Coder-Desktop/Coder-Desktop/Views/FileSync/FileSyncConfig.swift
- Coder-Desktop/Coder-Desktop/Views/FileSync/FileSyncSessionModal.swift
- Coder-Desktop/Coder-Desktop/Views/VPN/VPNMenu.swift
Previously, the agent/workspace picker when creating a file sync session had the user choose between instances of the `Agent` struct. This meant the value would get unselected were the status of the agent to change. I'm not sure why I had the picker select the entire struct instead of just the hostname.
> fix: improve file sync agent picker

- Coder-Desktop/Coder-Desktop/Info.plist
- Coder-Desktop/Coder-Desktop/Views/FileSync/FilePicker.swift
- Coder-Desktop/Coder-Desktop/Views/FileSync/FileSyncSessionModal.swift
- Coder-Desktop/Coder-DesktopTests/FilePickerTests.swift
- Coder-Desktop/Coder-DesktopTests/Util.swift
- Coder-Desktop/CoderSDK/AgentClient.swift
- Coder-Desktop/CoderSDK/AgentLS.swift
- Coder-Desktop/CoderSDK/Client.swift
Closes #65.
https://github.com/user-attachments/assets/f5f9ae14-7bfe-4520-8b05-a1ff8ad0ada0
https://github.com/user-attachments/assets/34706ed8-15db-409a-9a69-972fab75a3ae
> feat: add remote folder picker to file sync GUI

- Coder-Desktop/Coder-Desktop/Coder_DesktopApp.swift
- Coder-Desktop/Coder-Desktop/Preview Content/PreviewFileSync.swift
- Coder-Desktop/Coder-Desktop/Views/FileSync/FileSyncConfig.swift
- Coder-Desktop/Coder-Desktop/Views/FileSync/FileSyncSessionModal.swift
- Coder-Desktop/Coder-DesktopTests/FilePickerTests.swift
- Coder-Desktop/Coder-DesktopTests/FileSyncDaemonTests.swift
- Coder-Desktop/Coder-DesktopTests/Util.swift
- Coder-Desktop/VPNLib/FileSync/FileSyncDaemon.swift
- Coder-Desktop/VPNLib/FileSync/FileSyncManagement.swift
- Coder-Desktop/project.yml
- Makefile
These are just regression tests for the core file sync daemon functionality.
Also has sync sessions ignore VCS directories by default, as per the file sync RFC.
> chore: add file sync daemon tests

- Coder-Desktop/Coder-Desktop/State.swift
- Coder-Desktop/Coder-Desktop/Views/FileSync/FilePicker.swift
- Coder-Desktop/Coder-Desktop/Views/LoginForm.swift
- Coder-Desktop/Coder-DesktopTests/FilePickerTests.swift
- Coder-Desktop/Coder-DesktopTests/LoginFormTests.swift
- Coder-Desktop/CoderSDK/AgentClient.swift
- Coder-Desktop/CoderSDK/AgentLS.swift
- Coder-Desktop/CoderSDK/Client.swift
- Coder-Desktop/CoderSDK/Deployment.swift
- Coder-Desktop/CoderSDK/User.swift
- Coder-Desktop/CoderSDKTests/CoderSDKTests.swift
Refactor to address review feedback that `AgentClient` extending the regular `Client` was confusing.
> refactor(CoderSDK): share code between Client and AgentClient

- pkgbuild/scripts/postinstall
- pkgbuild/scripts/preinstall
One thing I noticed as part of my work on #121 is that our attempted fix introduced in #92 wasn't working as expected if the user had a VPN configuration installed before #86. 
This PR fetches the unique name of the VPN service dynamically, as part of the script, such that the service is started and stopped regardless of whether the service is called "Coder" or the older "CoderVPN".
This also ensures we don't break it again if we ever change that name, such as to "Coder Connect" (I don't totally recall why it was set to "Coder", but I don't mind it)
> fix: support old VPN config names in post & pre install scripts

- Coder-Desktop/Coder-Desktop/Coder_DesktopApp.swift
- Coder-Desktop/Coder-Desktop/State.swift
- Coder-Desktop/Coder-Desktop/Theme.swift
- Coder-Desktop/Coder-Desktop/Views/ResponsiveLink.swift
- Coder-Desktop/Coder-Desktop/Views/Util.swift
- Coder-Desktop/Coder-Desktop/Views/VPN/VPNMenuItem.swift
- Coder-Desktop/Coder-Desktop/Views/VPN/WorkspaceAppIcon.swift
- Coder-Desktop/Coder-DesktopTests/WorkspaceAppTests.swift
- Coder-Desktop/CoderSDK/Workspace.swift
- Coder-Desktop/project.yml
Closes #94.
https://github.com/user-attachments/assets/0777d1c9-6183-487d-b24a-b2ad9639d75b
The cursor does not change to a pointing hand as it should when screen-recording, and the display name of the app is also shown on hover:
As per the linked issue, this only shows the first five apps. If there's less than 5 apps, they won't be centered (I think this looks a bit better):
Later designs will likely include a Workspace window where all the apps can be viewed, and potentially reordered to control what is shown on the tray.
EDIT: Web apps have been filtered out of the above examples, as we don't currently have a way to determine whether they will work properly via Coder Connect.
> feat: add workspace apps

- Coder-Desktop/Coder-Desktop/Theme.swift
- Coder-Desktop/Coder-Desktop/VPN/MenuState.swift
- Coder-Desktop/Coder-Desktop/Views/VPN/Agents.swift
- Coder-Desktop/Coder-Desktop/Views/VPN/VPNMenuItem.swift
- Coder-Desktop/Coder-Desktop/Views/VPN/WorkspaceAppIcon.swift
- Coder-Desktop/Coder-DesktopTests/AgentsTests.swift
https://github.com/user-attachments/assets/3503bc17-1cfe-4747-97b4-0883e2763e74
> feat: make workspace apps collapsible

- pkgbuild/scripts/postinstall
- pkgbuild/scripts/preinstall
As part of my work on #121 and trying to reproduce the behaviour in a VM, I discovered the issue consistently occurs if the VPN is running when the app is launched (as the network extension is replaced on upgrade).
The existing pkgbuild scripts don't account for the VPN running with the app closed. 
In this scenario the `preinstall` script creates a marker file saying the VPN should be started in the `postinstall`. A marker file saying the app is running is not created. 
Then, in the `postinstall` the VPN is started, but not the app. When the user does launch the app, the network extension is upgraded whilst the VPN is running, and the linked issue occurs.
It's not possible to write a bash script that waits for not only the app to launch, but for the network extension replacement request …
> fix(pkgbuild): dont start coder connect after upgrade

- Coder-Desktop/VPN/Manager.swift
- Coder-Desktop/VPN/PacketTunnelProvider.swift
Closes #88.
With https://github.com/coder/internal/issues/563 resolved, there's no need to stop the VPN on sleep, as when the device wakes the tunnel will have the correct workspace & agent state.
However, if the Coder deployment doesn't include the patch in https://github.com/coder/coder/pull/17598 (presumably v2.23 or later), the UI state will go out of sync when the device is slept or internet connection is lost. I think this is fine honestly, and I don't think it's worth doing a server version check to determine whether we should stop the VPN on sleep.
> chore: dont stop coder connect on device sleep

- Coder-Desktop/Coder-Desktop/Coder_DesktopApp.swift
- Coder-Desktop/Coder-Desktop/State.swift
- Coder-Desktop/project.yml
Relates to #148.
If the menu bar icon is hidden (such as when behind the notch, or otherwise), reopening the app will display an alert that the icon is hidden.
There's also a button to not show the alert again.
I've also tested that this, and the 'Do not show again' button, work in a fresh VM.
This is the same as what Tailscale does:
https://github.com/user-attachments/assets/dae6d9ed-eab2-404f-8522-314042bdd1d8
> feat: show an alert when the menu bar icon is hidden

- Coder-Desktop/Coder-Desktop/Views/VPN/WorkspaceAppIcon.swift
- Coder-Desktop/Coder-DesktopTests/WorkspaceAppTests.swift
- Coder-Desktop/CoderSDK/Workspace.swift
also uses `code-insiders.svg` for the VS Code insiders icon.
Context: https://github.com/coder/coder/pull/17700
> fix: handle missing workspace app `display_name`

- Coder-Desktop/Coder-Desktop/Coder_DesktopApp.swift
- Coder-Desktop/Coder-Desktop/Notifications.swift
- Coder-Desktop/project.yml
Relates to #96.
I've had to replace the  **app** provisioning profile for this to build.
> feat: send push notifications for invalid `coder` scheme URIs

- Coder-Desktop/Coder-Desktop/State.swift
It's fair to assume if you're closing Coder Desktop, you want Coder Connect to stop, so this is the default behaviour.
Tailscale also stops their VPN when quitting the app, even though it works fine with the app closed.
> chore: set 'stop VPN on quit' setting to true by default

- Coder-Desktop/Coder-Desktop/VPN/NetworkExtension.swift
- Coder-Desktop/Coder-Desktop/VPN/VPNService.swift
- Coder-Desktop/Coder-Desktop/VPN/VPNSystemExtension.swift
- Coder-Desktop/Coder-Desktop/Views/VPN/VPNMenu.swift
- Coder-Desktop/Coder-Desktop/Views/VPN/VPNState.swift
This PR addresses #121. The underlying bug is still present in macOS, this is just a workaround, so I'm leaving the issue open.
macOS calls `actionForReplacingExtension` whenever the version string(s) of the system extension living inside the Coder Desktop app bundle change.
i.e. When a new version of the app is installed:
1. App sends `activationRequest` (it does this on every launch, to see if the NE is installed)
2. Eventually, `actionForReplacingExtension` is called, which can either return `.cancel` or `.replace`.
3. Eventually,`didFinishWithResult` is called with whether the replacement was successful.
(`actionForReplacingExtension` is *always* called when developing the app locally, even if the version string(s) don't differ)
However, in the linked issue, we note that this …
> fix: manually upgrade system extension

- Coder-Desktop/Coder-Desktop/VPN/VPNSystemExtension.swift
This fixes a bug when `Launch Coder Connect at startup` is enabled when updating the app with #161, where the app attempts to start too early, as it thinks the VPN is configured, but it was unconfigured with the deletion of the system extension.
> fix: set network extension as unconfigured when system extension is deleted

- Coder-Desktop/Coder-Desktop/Coder_DesktopApp.swift
- Coder-Desktop/Coder-Desktop/HelperService.swift
- Coder-Desktop/Coder-Desktop/Views/Settings/ExperimentalTab.swift
- Coder-Desktop/Coder-Desktop/Views/Settings/HelperSection.swift
- Coder-Desktop/Coder-Desktop/Views/Settings/Settings.swift
- Coder-Desktop/Coder-Desktop/XPCInterface.swift
- Coder-Desktop/Coder-DesktopHelper/HelperXPCProtocol.swift
- Coder-Desktop/Coder-DesktopHelper/com.coder.Coder-Desktop.Helper.plist
- Coder-Desktop/Coder-DesktopHelper/main.swift
- Coder-Desktop/VPN/AppXPCListener.swift
- Coder-Desktop/VPN/HelperXPCSpeaker.swift
- Coder-Desktop/VPN/Manager.swift
- Coder-Desktop/VPN/main.swift
- Coder-Desktop/VPNLib/FileSync/FileSyncDaemon.swift
- Coder-Desktop/project.yml
Closes #135.
Closes https://github.com/coder/coder-desktop-macos/issues/142.
This PR adds an optional privileged `LaunchDaemon` capable of removing the quarantine flag on a downloaded `.dylib` without prompting the user to enter their password. This is most useful when the Coder deployment updates frequently.
The System Extension communicates directly with the `LaunchDaemon`, meaning a new `.dylib` can be downloaded and executed even if the app was closed, which was previously not possible. 
I've tested this in a fresh 15.4 VM.
> feat: add experimental privileged helper

- Coder-Desktop/Coder-Desktop/Preview Content/PreviewVPN.swift
- Coder-Desktop/Coder-Desktop/VPN/VPNProgress.swift
- Coder-Desktop/Coder-Desktop/VPN/VPNService.swift
- Coder-Desktop/Coder-Desktop/Views/CircularProgressView.swift
- Coder-Desktop/Coder-Desktop/Views/VPN/Agents.swift
- Coder-Desktop/Coder-Desktop/Views/VPN/VPNState.swift
- Coder-Desktop/Coder-Desktop/XPCInterface.swift
- Coder-Desktop/Coder-DesktopTests/Util.swift
- Coder-Desktop/Coder-DesktopTests/VPNStateTests.swift
- Coder-Desktop/VPN/Manager.swift
- Coder-Desktop/VPN/PacketTunnelProvider.swift
- Coder-Desktop/VPNLib/Download.swift
- Coder-Desktop/VPNLib/Util.swift
- Coder-Desktop/VPNLib/XPC.swift
Closes #159.
https://github.com/user-attachments/assets/26391aef-31a1-4d5a-8db0-910a9fbe97ea
> feat: add coder connect startup progress indicator

- Coder-Desktop/Coder-Desktop/State.swift
If the session item in the keychain is missing but `hasSession` is true, the app will force unwrap the session token optional and crash on launch. Encountered this today.
> fix: don't create http client if signed out

- .github/actions/nix-devshell/action.yaml
It's twice as fast without the cache
With cache:
Without:
I can only assume it's just faster to compile some of the dependencies then to copy them from the cache
> ci: remove cache-nix-action

- .github/workflows/release.yml
- Coder-Desktop/Coder-Desktop/Coder_DesktopApp.swift
- Coder-Desktop/Coder-Desktop/Info.plist
- Coder-Desktop/Coder-Desktop/UpdaterService.swift
- Coder-Desktop/Coder-Desktop/VPN/VPNSystemExtension.swift
- Coder-Desktop/Coder-Desktop/Views/Settings/GeneralTab.swift
- Coder-Desktop/project.yml
- scripts/update-cask.sh
Closes #47.
Stable:
Preview:
Additionally:
- Removes the updating of the `coder-desktop-preview` cask. 
- Marks the `coder-desktop` cask as auto-updating, so brew doesn't attempt to `upgrade` itself.
I'll also need to make a PR on the `homebrew-coder` repo to mark it as deprecated in brew. If a user wishes to be on the preview channel, they just need to install the stable version, and switch to the preview channel in settings.
> feat: add auto-updates

- Coder-Desktop/Coder-Desktop/Theme.swift
- Coder-Desktop/Coder-Desktop/Views/FileSync/FileSyncConfig.swift
- Coder-Desktop/Coder-Desktop/Views/VPN/VPNMenuItem.swift
- Coder-Desktop/VPNLib/Download.swift
These changes were in response to feedback:
- Adds tooltips on hover to the copy DNS button, and the open in browser button on the main tray menu.
- Includes the download URL in the error message if the client receives an unexpected HTTP code when downloading.
- Makes the file sync table controls a lil bigger (24px -> 28px):
-  Before:
- ![](https://github.com/user-attachments/assets/01dabe2c-4571-4014-98b1-1d8daf603516)
- After:
- ![](https://github.com/user-attachments/assets/90192329-62f6-4ed2-a992-0cb9f73957a4)
> chore: minor ui/ux changes

- Coder-Desktop/Coder-Desktop/Info.plist
- Coder-Desktop/Coder-Desktop/VPN/VPNSystemExtension.swift
- Coder-Desktop/VPN/Info.plist
We append the CFBundleVersion to the service name to ensure a new service is used for each version. This works around the issue described in https://github.com/coder/coder-desktop-macos/issues/121, presumably caused by the XPC service cache not being invalidated on update.
> chore: append bundle version to mach service name

- Coder-Desktop/Coder-Desktop/Views/VPN/VPNMenu.swift
- Coder-Desktop/Coder-DesktopTests/VPNMenuTests.swift
I undid the work of #114 in #158, by disabling the VPN toggle when the network extension was unconfigured.
When signed out, the network extension is unconfigured.
This PR adds a special exception to make the VPN toggle always clickable when signed out, as it has special behaviour when signed out.
It also adds a proper regression test. A slightly different regression test existed, but it didn't account for cases where the VPN state is one that would normally disable the toggle.
> fix: prompt for sign in when toggling coder connect on

- Coder-Desktop/Coder-Desktop/VPN/NetworkExtension.swift
- Coder-Desktop/Coder-Desktop/VPN/VPNService.swift
- Coder-Desktop/project.yml
Some flakey OS operation has been reported by two different users after installation:
I don't know what's happening because the error handling here isn't very good. This PR fixes that by always including the operation that failed in the UI message.
> chore: improve vpn configuration errors

- Coder-Desktop/Coder-DesktopHelper/Manager.swift
- Coder-Desktop/VPNLib/Validate.swift
Relates to #201.
**After we've validated the binary signature**, we exec `coder version --output=json` to validate the version of the downloaded binary matches the server. This is done to prevent against downgrade attacks, and to match the checking we had on the dylib before.
Additionally, this PR also ensures the certificate used to sign the binary is part of an Apple-issued certificate chain.
I assumed we were checking this before (by default) but we weren't. 
Though we weren't previously checking it, we were only ever downloading and executing a dylib. 
My understanding is that macOS won't execute a dylib unless the executing process and the dylib were signed by the same Apple developer team (at [least in a sandboxed process](https://developer.apple.com/forums/thread/683914), as is the …
> chore: ensure downloaded slim binary version matches server

- pkgbuild/scripts/postinstall
This PR prevents issues like:
which occur when the app is launched as root. This can happen when the installer scripts are run as root, which is the case when deploying Coder Desktop over MDM. (As a convenience, we re-open the app if it was open before the installer was ran.)
Of note is that on macOS, it is not sufficient to just run open with `sudo -u`, as that does not use the execution context of the user. See https://developer.apple.com/forums/thread/78332
Reports of the bug in other programs:
(with an incorrect solution) https://community.zoom.com/t5/Zoom-Meetings/A-keychain-cannot-be-found-to-stoer-quot-Zoom-quot/m-p/51059 
https://displaylink.org/forum/showthread.php?p=97176
> fix: always open app as logged-in user in postinstall script

- Coder-Desktop/Coder-Desktop/Views/LoginForm.swift
Currently, in the Login Form, we reject non-https URLs. When this HTTPS requirement was added, the Coder Desktop app was unable to make HTTP requests, as it did not have `NSArbitraryLoads`. We ended up needing to enable that flag in order to use the Agent API. (`http://workspace.coder:4`)
To support Coder deployments behind VPNs without HTTPS, we can now loosen the requirement. With this PR, the behavior [matches Windows.](https://github.com/coder/coder-desktop-windows/blob/ac22fe4c44dea03b21557b4a0f1e214397bc3ea4/App/Services/CredentialManager.cs#L175-L176)
> feat: support http coder urls

- Coder-Desktop/Coder-Desktop/Views/VPN/VPNState.swift
I added this block of code as a convenience, during the time we were using a workaround for the XPC issue that involved deleting and reinserting the network extension when updated. This block of code meant the user didn't need to click back into the tray menu to get the VPN configuration prompt to appear, it would just appear as soon as necessary.
However, this introduces a race. If the app loads the VPN unconfigured view before the task that checks for an existing VPN configuration finishes (this task runs as part of `applicationDidFinishLaunching`), the user will be displayed the prompt to reconfigure, even if a valid configuration already exists.
Since we're not using the aforementioned workaround, this convenience is no longer necessary, and can be removed as the race is more likely …
> fix: avoid automatically reconfiguring vpn

- Coder-Desktop/Coder-Desktop/UpdaterService.swift
- Coder-Desktop/Coder-Desktop/VPN/VPNService.swift
- Coder-Desktop/Coder-Desktop/Views/FileSync/FilePicker.swift
- Coder-Desktop/Coder-Desktop/Views/Settings/GeneralTab.swift
Closes #182.
UserDefaults can be forcibly set by MDM admins. 
When the `disableUpdater` bool in UserDefaults is set to `false`, the updater won't be initialized on launch, and the UI elements for the updater in settings will be hidden.
Related to #220.
> feat: support disabling the built-in updater

- scripts/update-cask.sh
Noticed when making the new release that this was wrong... Obviously not essential since I assume everyone's on arm64 these days.
> ci: fix typo in brew cask zap stanza

- Coder-Desktop/Coder-Desktop/Coder_DesktopApp.swift
- Coder-Desktop/Coder-Desktop/Views/Util.swift
This was requested once or twice, but until I saw Tailscale do it I thought it wasn't possible! The main motivation is so you can cmd+tab back into the sign in window once you have the token, or click the dock icon.
Pretty sure this is the same way Tailscale does it.
https://github.com/user-attachments/assets/a2e6a5de-dc4b-4cf3-8896-2255381efa9e
> feat: dynamically show app in dock & cmd+tab
